spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
  session:
    jdbc:
      initialize-schema: always
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: debug


server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
        name: SESSION
        path: /
      timeout: 30m
  tomcat:
    connection-timeout: 300000
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: tomcat
    key-store-type: pkcs12
    enabled: true